### PR TITLE
Fixed pagination URLs

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by SimonMueller** [comment]
Hey there and thank you for being the first contributor to this theme! 🥇 

Could you please explain your issue with the current implementation or why you want to change the pagination URL's? It seems correct to me because if `base_url` is an absolute path you would remove the double slash from e.g. `https://example.com` if you include it in the replacement...

(The official pagination plugin does it this way aswell: https://github.com/getgrav/grav-plugin-pagination/blob/develop/templates/partials/pagination.html.twig

**Comment by nicosomb** [comment]
Hello @SimonMueller. 
I installed your theme on my blog (https://nicolas.loeuillet.org/) and the default pagination didn't work. 
So I had a look on a theme which works for me: https://github.com/getgrav/grav-theme-saturn/blob/develop/templates/partials/pagination.html.twig

**Comment by SimonMueller** [comment]
I tested the saturn theme now and it really strips the double slashed from an absolute path which is not the correct behaviour in my opinion. Meanwhile it works  for me with the pluspunkt theme in both cases (absolute an relative). I tested it in Safari and Firefox.

Can you provide some html from the generated next or previous url where the error happens?
I hope we can figure this out soon!

**Comment by nicosomb** [comment]
I removed my fix on my blog https://nicolas.loeuillet.org/

**Comment by SimonMueller** [comment]
I found the issue. It was because your blog page is at the root path of your domain and therefore the path is `/`. This leads us to an edge case where a relative URL with pagination can become something like `/`+ `/page:2`= `//page:2. In this case the replacement of double slashes is the solution. But in Grav you are able to select between to URL types:

1. Absolute URLs (System config)
If we replace the double slash in an absolute path it fails because of the earlier mentioned `https://` which will become `https:/`which is not a correct URL. The pagination plugin does not account for that in the current release and absolute URLs break. (The link i sent was accidentally taken from the develop branch)

2. Relative URLs (Default System config)
It is no problem to replace the double slashes in the entire URL. The pluspunkt theme is optimized for absolute URLs because of my preference in terms of SOE. 

So as a fix i would recommend a check in the beginning of the pagination template to check if the path is equal to `/`and just replace it with an empty string. This fix works in both cases. :)

**Comment by SimonMueller** [comment]
see #15 for fix

**Pull request closed without merging**
